-- ==============================================================================
-- Suggula's Kitchen - Complete Supabase Database Schema
-- ==============================================================================

-- ------------------------------------------------------------------------------
-- 1. Security Functions
-- ------------------------------------------------------------------------------
-- Defines who is an admin. Since public signup is disabled, any authenticated user
-- is treated as an admin.
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean
LANGUAGE sql
SECURITY DEFINER
AS $$
  SELECT auth.uid() IS NOT NULL;
$$;

-- ------------------------------------------------------------------------------
-- 2. Table Definitions
-- ------------------------------------------------------------------------------

-- BUSINESS
CREATE TABLE IF NOT EXISTS public.business (
  id bigint generated by default as identity primary key,
  name text,
  tagline text,
  description text,
  "aboutTitle" text,
  about text,
  mission text,
  vision text,
  phone text,
  whatsapp text,
  email text,
  address text,
  hours text,
  "footerText" text,
  "socialLinks" jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

-- CUSTOMERS
CREATE TABLE IF NOT EXISTS public.customers (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null,
  address text not null,
  created_at timestamptz not null default now()
);

-- ORDERS
CREATE TABLE IF NOT EXISTS public.orders (
  id bigint generated by default as identity primary key,
  customer_id bigint references public.customers(id) on delete cascade,
  items jsonb not null default '[]'::jsonb,
  total numeric(10, 2) not null,
  status text not null default 'pending',
  created_at timestamptz not null default now()
);

-- SHIPPING INFORMATION
CREATE TABLE IF NOT EXISTS public.shipping_information (
  id bigint generated by default as identity primary key,
  order_id bigint references public.orders(id) on delete cascade,
  customer_id bigint references public.customers(id) on delete cascade,
  delivery_partner_name text,
  tracking_link text,
  delivery_date date,
  shipping_date date,
  delivery_status text not null default 'pending',
  created_at timestamptz not null default now()
);

-- CATEGORIES
CREATE TABLE IF NOT EXISTS public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  status text not null default 'active',
  created_at timestamptz not null default now()
);

-- PRODUCTS
CREATE TABLE IF NOT EXISTS public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text,
  categories_id bigint references public.categories(id) on delete set null,
  price numeric(10, 2),
  actual_price numeric(10, 2),
  current_price numeric(10, 2),
  availability boolean not null default true,
  created_at timestamptz not null default now()
);

-- MENUS (Legacy structure)
CREATE TABLE IF NOT EXISTS public.menus (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  actual_price numeric(10, 2),
  current_price numeric(10, 2),
  photo_url text,
  available boolean not null default true,
  created_at timestamptz not null default now()
);

-- GALLERY
CREATE TABLE IF NOT EXISTS public.gallery (
  id bigint generated by default as identity primary key,
  title text,
  description text,
  "imageUrl" text,
  image_url text,
  "mediaType" text default 'image',
  media_type text default 'image',
  "mediaUrl" text,
  media_url text,
  created_at timestamptz not null default now()
);

-- ------------------------------------------------------------------------------
-- 3. Row Level Security (RLS) Policies
-- ------------------------------------------------------------------------------

-- Enable RLS on all public tables
ALTER TABLE public.business ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.shipping_information ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.menus ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gallery ENABLE ROW LEVEL SECURITY;

-- BUSINESS: Public read, Admin write
DROP POLICY IF EXISTS "Public can read business content" ON public.business;
CREATE POLICY "Public can read business content" ON public.business FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "Admins can write business content" ON public.business;
CREATE POLICY "Admins can write business content" ON public.business FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());

-- CUSTOMERS: Admin all (Private data)
DROP POLICY IF EXISTS "Admins can manage customers" ON public.customers;
CREATE POLICY "Admins can manage customers" ON public.customers FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());

-- ORDERS: Admin all (Private data)
DROP POLICY IF EXISTS "Admins can manage orders" ON public.orders;
CREATE POLICY "Admins can manage orders" ON public.orders FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());

-- SHIPPING INFORMATION: Admin all (Private data)
DROP POLICY IF EXISTS "Admins can manage shipping information" ON public.shipping_information;
CREATE POLICY "Admins can manage shipping information" ON public.shipping_information FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());

-- CATEGORIES: Public read, Admin write
DROP POLICY IF EXISTS "Public can read categories" ON public.categories;
CREATE POLICY "Public can read categories" ON public.categories FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "Admins can write categories" ON public.categories;
CREATE POLICY "Admins can write categories" ON public.categories FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());

-- PRODUCTS: Public read, Admin write
DROP POLICY IF EXISTS "Public can read products" ON public.products;
CREATE POLICY "Public can read products" ON public.products FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "Admins can write products" ON public.products;
CREATE POLICY "Admins can write products" ON public.products FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());

-- MENUS: Public read, Admin write
DROP POLICY IF EXISTS "Public can read menus" ON public.menus;
CREATE POLICY "Public can read menus" ON public.menus FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "Admins can write menus" ON public.menus;
CREATE POLICY "Admins can write menus" ON public.menus FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());

-- GALLERY: Public read, Admin write
DROP POLICY IF EXISTS "Public can read gallery records" ON public.gallery;
CREATE POLICY "Public can read gallery records" ON public.gallery FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "Admins can manage gallery records" ON public.gallery;
CREATE POLICY "Admins can manage gallery records" ON public.gallery FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());

-- ------------------------------------------------------------------------------
-- 4. Storage Buckets & Policies
-- ------------------------------------------------------------------------------

-- Create gallery bucket if it doesn't exist and make it public
INSERT INTO storage.buckets (id, name, public) VALUES ('gallery', 'gallery', true) ON CONFLICT (id) DO UPDATE SET public = true;
INSERT INTO storage.buckets (id, name, public) VALUES ('menu-photos', 'menu-photos', true) ON CONFLICT (id) DO UPDATE SET public = true;

-- Gallery Bucket Policies
DROP POLICY IF EXISTS "Authenticated users can view gallery images" ON storage.objects;
CREATE POLICY "Authenticated users can view gallery images" ON storage.objects FOR SELECT TO anon, authenticated USING (bucket_id = 'gallery');
DROP POLICY IF EXISTS "Admins can upload gallery images" ON storage.objects;
CREATE POLICY "Admins can upload gallery images" ON storage.objects FOR INSERT TO authenticated WITH CHECK (bucket_id = 'gallery' AND public.is_admin());
DROP POLICY IF EXISTS "Admins can update gallery images" ON storage.objects;
CREATE POLICY "Admins can update gallery images" ON storage.objects FOR UPDATE TO authenticated USING (bucket_id = 'gallery' AND public.is_admin()) WITH CHECK (bucket_id = 'gallery' AND public.is_admin());
DROP POLICY IF EXISTS "Admins can delete gallery images" ON storage.objects;
CREATE POLICY "Admins can delete gallery images" ON storage.objects FOR DELETE TO authenticated USING (bucket_id = 'gallery' AND public.is_admin());

-- Menu Photos Bucket Policies
DROP POLICY IF EXISTS "Authenticated users can view menu photos" ON storage.objects;
CREATE POLICY "Authenticated users can view menu photos" ON storage.objects FOR SELECT TO anon, authenticated USING (bucket_id = 'menu-photos');
DROP POLICY IF EXISTS "Admins can upload menu photos" ON storage.objects;
CREATE POLICY "Admins can upload menu photos" ON storage.objects FOR INSERT TO authenticated WITH CHECK (bucket_id = 'menu-photos' AND public.is_admin());
DROP POLICY IF EXISTS "Admins can update menu photos" ON storage.objects;
CREATE POLICY "Admins can update menu photos" ON storage.objects FOR UPDATE TO authenticated USING (bucket_id = 'menu-photos' AND public.is_admin()) WITH CHECK (bucket_id = 'menu-photos' AND public.is_admin());
DROP POLICY IF EXISTS "Admins can delete menu photos" ON storage.objects;
CREATE POLICY "Admins can delete menu photos" ON storage.objects FOR DELETE TO authenticated USING (bucket_id = 'menu-photos' AND public.is_admin());

-- ------------------------------------------------------------------------------
-- 5. PostgREST Reload
-- ------------------------------------------------------------------------------
NOTIFY pgrst, 'reload schema';
