-- ==============================================================================
-- Suggula's Kitchen - Complete Supabase Database Schema
-- Run this entire file in the Supabase SQL Editor to set up your database.
-- Safe to re-run on an existing database - will not delete data.
-- ==============================================================================

-- 1. SECURITY FUNCTION

-- Create the VIP list (admins table)
CREATE TABLE IF NOT EXISTS public.admins (
  user_id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at timestamptz DEFAULT now()
);

-- Add yourself to the VIP list (REPLACE THE TEXT IN THE QUOTES!)
INSERT INTO public.admins (user_id)
VALUES ('PASTE-YOUR-COPIED-UUID-HERE')
ON CONFLICT DO NOTHING;

-- Update the rule to check the VIP list
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.admins WHERE user_id = auth.uid()
  );
$$;

-- Secure the SECURITY DEFINER function
REVOKE EXECUTE ON FUNCTION public.is_admin() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.is_admin() TO authenticated, service_role;

-- 2. TABLE DEFINITIONS

CREATE TABLE IF NOT EXISTS public.business (
  id            bigint generated by default as identity primary key,
  name          text, tagline text, description text,
  "aboutTitle"  text, about text, mission text, vision text,
  phone text, whatsapp text, email text, address text, hours text,
  "footerText"  text,
  "socialLinks" jsonb not null default '[]'::jsonb,
  hero_image_1_id bigint,
  hero_image_2_id bigint,
  hero_bg_color text not null default '#26351c',
  created_at    timestamptz not null default now()
);

-- Note: We cannot easily add foreign keys to the table definition here because gallery is defined below.
-- So we add them as ALTER TABLE statements later in the schema script.

-- Gallery must come before categories/products (they reference it via image_id)
CREATE TABLE IF NOT EXISTS public.gallery (
  id          bigint generated by default as identity primary key,
  title       text, description text,
  image_url   text,
  media_type  text default 'image',
  media_url   text,
  status      text not null default 'active',
  created_at  timestamptz not null default now()
);

CREATE TABLE IF NOT EXISTS public.categories (
  id           bigint generated by default as identity primary key,
  name         text not null, description text, "priceRange" text,
  featured     boolean not null default false,
  status       text not null default 'active',
  image_id     bigint references public.gallery(id) on delete set null,
  created_at   timestamptz not null default now()
);

-- availability is stored as text ('available'/'unavailable') to match api.js
CREATE TABLE IF NOT EXISTS public.products (
  id                  bigint generated by default as identity primary key,
  name                text not null, category text,
  categories_id       bigint references public.categories(id) on delete set null,
  "shortDescription"  text,
  price               numeric(10,2), actual_price numeric(10,2), current_price numeric(10,2),
  availability        text not null default 'available',
  featured            boolean not null default false,
  "bestSeller"        boolean not null default false,
  "newArrival"        boolean not null default false,
  veg                 boolean not null default false,
  "preparationTime"   integer, ingredients text, "spiceLevel" text,
  image_id            bigint references public.gallery(id) on delete set null,
  created_at          timestamptz not null default now()
);

CREATE TABLE IF NOT EXISTS public.menus (
  id bigint generated by default as identity primary key,
  name text not null, description text,
  actual_price numeric(10,2), current_price numeric(10,2),
  photo_url text, available boolean not null default true,
  created_at timestamptz not null default now()
);

CREATE TABLE IF NOT EXISTS public.customers (
  id bigint generated by default as identity primary key,
  name text not null, phone text not null, address text not null,
  created_at timestamptz not null default now()
);

CREATE TABLE IF NOT EXISTS public.orders (
  id bigint generated by default as identity primary key,
  customer_id bigint references public.customers(id) on delete cascade,
  items jsonb not null default '[]'::jsonb,
  total numeric(10,2) not null, status text not null default 'pending',
  created_at timestamptz not null default now()
);

CREATE TABLE IF NOT EXISTS public.shipping_information (
  id bigint generated by default as identity primary key,
  order_id bigint references public.orders(id) on delete cascade,
  customer_id bigint references public.customers(id) on delete cascade,
  delivery_partner_name text, tracking_link text,
  delivery_date date, shipping_date date,
  delivery_status text not null default 'pending',
  created_at timestamptz not null default now()
);

-- 3. ADD MISSING COLUMNS TO EXISTING TABLES (safe to re-run)

ALTER TABLE public.gallery ADD COLUMN IF NOT EXISTS status text not null default 'active';

ALTER TABLE public.categories ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE public.categories ADD COLUMN IF NOT EXISTS "priceRange" text;
ALTER TABLE public.categories ADD COLUMN IF NOT EXISTS featured boolean not null default false;
ALTER TABLE public.categories ADD COLUMN IF NOT EXISTS status text not null default 'active';
ALTER TABLE public.categories ADD COLUMN IF NOT EXISTS image_id bigint references public.gallery(id) on delete set null;

ALTER TABLE public.products ADD COLUMN IF NOT EXISTS "shortDescription" text;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS featured boolean not null default false;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS "bestSeller" boolean not null default false;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS "newArrival" boolean not null default false;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS veg boolean not null default false;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS "preparationTime" integer;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS ingredients text;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS "spiceLevel" text;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS image_id bigint references public.gallery(id) on delete set null;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS actual_price numeric(10,2);
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS current_price numeric(10,2);

ALTER TABLE public.shipping_information ADD COLUMN IF NOT EXISTS tracking_link text;
ALTER TABLE public.shipping_information ADD COLUMN IF NOT EXISTS delivery_partner_name text;

-- Backfill prices for existing products
UPDATE public.products
SET actual_price = coalesce(actual_price, price),
    current_price = coalesce(current_price, price)
WHERE actual_price IS NULL OR current_price IS NULL;

ALTER TABLE public.business ADD COLUMN IF NOT EXISTS hero_image_1_id bigint references public.gallery(id) on delete set null;
ALTER TABLE public.business ADD COLUMN IF NOT EXISTS hero_image_2_id bigint references public.gallery(id) on delete set null;
ALTER TABLE public.business ADD COLUMN IF NOT EXISTS hero_bg_color text not null default '#26351c';

-- 4. ROW LEVEL SECURITY

ALTER TABLE public.business ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gallery ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.shipping_information ENABLE ROW LEVEL SECURITY;

-- Business: public read, admin write
DROP POLICY IF EXISTS "Public can read business content" ON public.business;
CREATE POLICY "Public can read business content" ON public.business FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "Admins can write business content" ON public.business;
CREATE POLICY "Admins can write business content" ON public.business FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());

-- Gallery: public read, admin write
DROP POLICY IF EXISTS "Public can read gallery records" ON public.gallery;
CREATE POLICY "Public can read gallery records" ON public.gallery FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "Admins can manage gallery records" ON public.gallery;
CREATE POLICY "Admins can manage gallery records" ON public.gallery FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());

-- Categories: public read, admin write
DROP POLICY IF EXISTS "Public can read categories" ON public.categories;
CREATE POLICY "Public can read categories" ON public.categories FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "Admins can write categories" ON public.categories;
CREATE POLICY "Admins can write categories" ON public.categories FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());

-- Products: public read, admin write
DROP POLICY IF EXISTS "Public can read products" ON public.products;
CREATE POLICY "Public can read products" ON public.products FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "Admins can write products" ON public.products;
CREATE POLICY "Admins can write products" ON public.products FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());


-- Customers: Drop-Box slot
-- 1. Clean the slate (Drop the old rules AND the new ones if they already exist)
DROP POLICY IF EXISTS "Customers can create their own record" ON public.customers;
DROP POLICY IF EXISTS "Customers can read their own record" ON public.customers;
DROP POLICY IF EXISTS "Anyone can create a customer record" ON public.customers;
DROP POLICY IF EXISTS "Admins can read customers" ON public.customers;
DROP POLICY IF EXISTS "Admins can manage customers" ON public.customers;

-- 2. Create the "Drop-Box" slot: Allow anyone to insert a new customer record
CREATE POLICY "Anyone can create a customer record"
ON public.customers
FOR INSERT
TO anon, authenticated
WITH CHECK (true);

-- 3. Lock the box: Only verified admins can read the customer list
CREATE POLICY "Admins can read customers"
ON public.customers
FOR SELECT
TO authenticated
USING (public.is_admin());

-- 4. Admin control: Only verified admins can edit or delete customers
CREATE POLICY "Admins can manage customers"
ON public.customers
FOR ALL
TO authenticated
USING (public.is_admin())
WITH CHECK (public.is_admin());

-- Orders: admin full access + anon insert (required by placeOrder/submitOrder in api.js)
DROP POLICY IF EXISTS "Admins can manage orders" ON public.orders;
CREATE POLICY "Admins can manage orders" ON public.orders FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());
DROP POLICY IF EXISTS "Customers can place orders" ON public.orders;
CREATE POLICY "Customers can place orders" ON public.orders FOR INSERT TO anon WITH CHECK (true);

-- Shipping: admin only
DROP POLICY IF EXISTS "Admins can manage shipping information" ON public.shipping_information;
CREATE POLICY "Admins can manage shipping information" ON public.shipping_information FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());

-- 5. STORAGE BUCKETS

INSERT INTO storage.buckets (id, name, public) VALUES ('gallery', 'gallery', true) ON CONFLICT (id) DO UPDATE SET public = true;


DROP POLICY IF EXISTS "Public can view gallery images" ON storage.objects;
DROP POLICY IF EXISTS "Admins can list gallery images" ON storage.objects;
CREATE POLICY "Admins can list gallery images" ON storage.objects FOR SELECT TO authenticated USING (bucket_id = 'gallery' AND public.is_admin());
DROP POLICY IF EXISTS "Admins can upload gallery images" ON storage.objects;
CREATE POLICY "Admins can upload gallery images" ON storage.objects FOR INSERT TO authenticated WITH CHECK (bucket_id = 'gallery' AND public.is_admin());
DROP POLICY IF EXISTS "Admins can update gallery images" ON storage.objects;
CREATE POLICY "Admins can update gallery images" ON storage.objects FOR UPDATE TO authenticated USING (bucket_id = 'gallery' AND public.is_admin()) WITH CHECK (bucket_id = 'gallery' AND public.is_admin());
DROP POLICY IF EXISTS "Admins can delete gallery images" ON storage.objects;
CREATE POLICY "Admins can delete gallery images" ON storage.objects FOR DELETE TO authenticated USING (bucket_id = 'gallery' AND public.is_admin());



-- 6. RELOAD
NOTIFY pgrst, 'reload schema';


-- 7. SECURE ORDER PRICING TRIGGER
-- Prevents clients from spoofing the total price. Recalculates total securely on the server.
CREATE OR REPLACE FUNCTION public.recalculate_order_total()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS \$\$
DECLARE
  item_record jsonb;
  product_price numeric;
  calculated_total numeric := 0;
BEGIN
  -- Loop through each item in the JSON array
  FOR item_record IN SELECT * FROM jsonb_array_elements(NEW.items)
  LOOP
    -- Get the genuine current_price from the products table
    SELECT coalesce(current_price, price, 0) INTO product_price
    FROM public.products
    WHERE id = (item_record->>'id')::bigint;

    IF NOT FOUND THEN
      RAISE EXCEPTION 'Product ID % not found. Cannot process order.', item_record->>'id';
    END IF;

    -- Add to the running total (price * quantity)
    calculated_total := calculated_total + (product_price * coalesce((item_record->>'quantity')::numeric, 1));
  END LOOP;

  -- Overwrite the client-provided total with the secure database-calculated total
  NEW.total := calculated_total;
  
  RETURN NEW;
END;
\$\$;

-- Secure the SECURITY DEFINER function
REVOKE EXECUTE ON FUNCTION public.recalculate_order_total() FROM PUBLIC;

DROP TRIGGER IF EXISTS enforce_secure_order_total ON public.orders;
CREATE TRIGGER enforce_secure_order_total
  BEFORE INSERT OR UPDATE ON public.orders
  FOR EACH ROW
  EXECUTE FUNCTION public.recalculate_order_total();
