create table if not exists public.business (
  id bigint generated by default as identity primary key,
  name text,
  tagline text,
  description text,
  "aboutTitle" text,
  about text,
  mission text,
  vision text,
  phone text,
  whatsapp text,
  email text,
  address text,
  hours text,
  "footerText" text,
  "socialLinks" jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.business enable row level security;

grant select on public.business to anon, authenticated;
grant insert, update on public.business to authenticated;

drop policy if exists "Public can read business content" on public.business;
create policy "Public can read business content"
on public.business
for select
to anon, authenticated
using (true);

drop policy if exists "Admins can write business content" on public.business;
create policy "Admins can write business content"
on public.business
for all
to authenticated
using (true)
with check (true);

grant select, insert, update, delete on public.gallery to authenticated;

drop policy if exists "Admins can manage gallery records" on public.gallery;
create policy "Admins can manage gallery records"
on public.gallery
for all
to authenticated
using (true)
with check (true);

alter table public.products
  add column if not exists actual_price numeric(10, 2),
  add column if not exists current_price numeric(10, 2);

-- Keep gallery records compatible with both existing camelCase data and the
-- snake_case columns used by the public API.
alter table public.gallery
  add column if not exists "imageUrl" text,
  add column if not exists image_url text,
  add column if not exists "mediaType" text default 'image',
  add column if not exists media_type text,
  add column if not exists "mediaUrl" text,
  add column if not exists media_url text;

grant select on public.gallery to anon, authenticated;

drop policy if exists "Public can read gallery records" on public.gallery;
create policy "Public can read gallery records"
on public.gallery
for select
to anon, authenticated
using (true);

update public.gallery
set "imageUrl" = coalesce("imageUrl", image_url),
    image_url = coalesce(image_url, "imageUrl"),
    "mediaType" = coalesce("mediaType", media_type, 'image'),
    media_type = coalesce(media_type, "mediaType", 'image'),
    "mediaUrl" = coalesce("mediaUrl", media_url),
    media_url = coalesce(media_url, "mediaUrl")
where true;

update public.products
set actual_price = coalesce(actual_price, price),
    current_price = coalesce(current_price, price)
where actual_price is null or current_price is null;

alter table public.shipping_information
  add column if not exists tracking_link text,
  add column if not exists delivery_partner_name text;

notify pgrst, 'reload schema';

grant select, insert, update on public.shipping_information to authenticated;

drop policy if exists "Admins can manage shipping information" on public.shipping_information;
create policy "Admins can manage shipping information"
on public.shipping_information
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

insert into storage.buckets (id, name, public)
values ('gallery', 'gallery', false)
on conflict (id) do update set public = false;

grant select, insert, update, delete on storage.objects to authenticated;

drop policy if exists "Public can view gallery images" on storage.objects;
drop policy if exists "Authenticated users can view gallery images" on storage.objects;
create policy "Authenticated users can view gallery images"
on storage.objects
for select
to authenticated
using (bucket_id = 'gallery');

drop policy if exists "Admins can upload gallery images" on storage.objects;
create policy "Admins can upload gallery images"
on storage.objects
for insert
to authenticated
with check (bucket_id = 'gallery');

drop policy if exists "Admins can update gallery images" on storage.objects;
create policy "Admins can update gallery images"
on storage.objects
for update
to authenticated
using (bucket_id = 'gallery')
with check (bucket_id = 'gallery');

drop policy if exists "Authenticated users can delete gallery images" on storage.objects;
create policy "Authenticated users can delete gallery images"
on storage.objects
for delete
to authenticated
using (bucket_id = 'gallery');
