export {
  fetchAppData,
  fetchDashboardCounts,
  fetchBusinessInfo,
  updateBusinessInfo,
  fetchCategories,
  createCategory,
  updateCategory,
  deleteCategory,
  fetchProducts,
  createProduct,
  updateProduct,
  deleteProduct,
  fetchGalleryItems,
  createGalleryItem,
  updateGalleryItem,
  deleteGalleryItem,
  fetchTestimonials,
  createTestimonial,
  updateTestimonial,
  deleteTestimonial,
  getMenu,
  getOrCreateCustomer,
  placeOrder,
  submitOrder,
  uploadImage
} from './supabase/api'
